### ISSUE TITLE
Unable to see stats of equipment along the bottom without equipping them, tooltip goes off screen.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1022]
DQO solved this by having the stats be on the top, not under the flavor text.

![ze](https://cloud.githubusercontent.com/assets/19625520/16028254/8c961b8e-31ab-11e6-9d22-7ac1e3522afc.png)

**Comment by ManDude** [comment]
All tooltips have the possibility of going off-screen (mod in an enemy with lots of immunities then check them in the battle info menu before starting a battle, for example).

**Comment by larsiusprime** [comment]
There's supposed to be built in functionality to tooltips to keep them from
going of screen and re-anchor themselves accordingly. Obviously it breaks
in some edge cases, but I'll fix this post launch.

On Tue, Jun 14, 2016 at 9:15 AM, ManDude <notifications@github.com> wrote:

> All tooltips have the possibility of going off-screen (mod in an enemy
> with lots of immunities then check them in the battle info menu before
> starting a battle, for example).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/1022#issuecomment-225894722>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-CJ5QOtu__TAN3G74536rCkl_J27ks5qLreOgaJpZM4I04DX>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Garryl** [comment]
Hi. I just want to confirm that this issue is still present as of March 2017. In the screenshot below, Eye of the Flame+ should display its second extra property:
vs Dark: Adds LIGHT:
10 sec, 100% chance

![screen shot 2017-03-21 at 1 16 08 pm](https://cloud.githubusercontent.com/assets/3309272/24160674/dde7441c-0e38-11e7-95ce-e24c8f7ded3b.jpg)

I'm running Mac OS 10.11.6 (El Capitan). My monitor has a resolution of 1680x1050, and my game is running in windowed mode at 1600x900. I am playing Defender's Quest Deluxe, 64-bit OpenGL, version Steam DQ1 2.1.5a.

**Comment by larsiusprime** [comment]
This will be fixed in the next build.
