### ISSUE TITLE
World map off center in widescreen mode

### ISSUE THREAD

**Issue by dkwasny** [larsiusprime/tdrpg-bugs#1056]
# Basic Info

Windows 10
Download (Steam)
Full Version
Version # 2.0.0
# Steps to Reproduce

Enter the world map on a widescreen resolution.
Both fullscreen and windowed modes are affected.
# What I expected to happen:

I expected the character to be positioned near the center of the screen as seen in 4:3 resolutions.
![dq-4-3](https://cloud.githubusercontent.com/assets/1449712/16102670/a9b875d2-333f-11e6-82ad-260d77aa6853.png)
# What happened instead:

The character is actually positioned towards the bottom when using 16:9 resolutions.
![dq-16-9](https://cloud.githubusercontent.com/assets/1449712/16102695/e5d41206-333f-11e6-97cf-d0794c0c7371.png)
This can make selecting levels below the one you are currently on cumbersome.
This was mentioned in [another issue](https://github.com/larsiusprime/tdrpg-bugs/issues/806#issuecomment-222875905), but might of been missed.

Of course users can use the arrow keys to pan the camera downwards to get a better view of the map, but the camera will lock back on to the character once you select a new level.

Using a 4:3 resolution is a fine enough workaround for me, but this might be enough to agitate some players.

**Comment by Landiss** [comment]
This bug is even more irritating with ultrawide resolution (21:9, in my case 3440x1440). When you move on the bottom of the global map (for example like on the screens above), the camera autopositions itself so high that the character cannot be seen at all (you have to move the camera down manually each time you move).

I don't know if such resolutions are officially supported, probably not, but would be nice if it could be fixed.
