### ISSUE TITLE
Markos replaced by green stickman?

### ISSUE THREAD

**Issue by NiBii** [larsiusprime/tdrpg-bugs#1134]
Operating System: Windows 7
Browser/Download: Download (DRM-Free, Humble Bundle-Edition)
Demo/Full?      : Full Version
Version #       : 2.0.0
Optional Info : I was trying to talk to Markos in a cutscene; most of his sprites were fine, but one of them seems to be a little messed up. I am using the original "old" cutscenes.
The first cutscenes in which this error occurred were Chapter IV, Scene 3: Meet the Knight and Scene 4: A Word of Warning. 
Image: http://oi68.tinypic.com/2v2gme8.jpg

Just did a quick research; the displayed stickman is listed as "image_not_found.png" in the "cutscenes" folder, it looks like something went wrong when it tried to load one of his cutscene sprites then, hope that helped.

**Comment by dawelty** [comment]
I got this same bug in Act IV Scene 1: Jewel of the Desert

Steps to replicate:

1. Play the movie: Act IV Scene 1: Jewel of the Desert
2. Hit next until Bakal first appears, immediately after Slak calls the enemy "effeminate baboons"
3. Hit the back button to go to the slide before Bakal appears.

The first time you do this you'll get a green stick figure with a transparent background replacing Bakal instead of the expected no-character-at-all.

If you repeat steps 2 and 3, hitting next to bring Bakal in, and then hitting back to see the stick figure again, it will now have a red-tinted background instead of a transparent one.


OS: Linux Mint 17.3
Kernel: 3.19.0-32-generic
Demo/Full: Full Version
Version #: 2.0.7a (Steam)

**Comment by IBwWG** [comment]
Confirmed exact same results as @DanWelty .  
2.1.2c - steam, Linux Mint 18.1 x64, HD mode@1920x1080 fullscreen
