### ISSUE TITLE
Localization: Some strings unstranslated in Spanish

### ISSUE THREAD

**Issue by FelipeMercader** [larsiusprime/tdrpg-bugs#1189]
Operating System: Windows 8.1
Steam version (public beta)
Version#: 2.0.7. a

Some strings unstranslated here and there. It seems that it does not follow a pattern.

![image](https://cloud.githubusercontent.com/assets/19960780/16685021/999a3516-4508-11e6-8d2f-f2d45b37fc1f.png)

![image](https://cloud.githubusercontent.com/assets/19960780/16685150/64dd6be4-4509-11e6-974c-bc197f374079.png)

![image](https://cloud.githubusercontent.com/assets/19960780/16685070/d1d1b17a-4508-11e6-95b7-6792ecaf4f62.png)

Weird because sometimes it is ok, even in the same battle, for instance:

![image](https://cloud.githubusercontent.com/assets/19960780/16685087/f3fd32ba-4508-11e6-848c-b475c4db56c8.png)

![image](https://cloud.githubusercontent.com/assets/19960780/16685919/abf2c8a8-450e-11e6-9db5-8c023a518416.png)

**Comment by LarsMadeMeDoIt** [comment]
There are 3 different issues here:

- For DQDX the book reward text has been moved to a separate file (goodies.tsv) which is not present in the Spanish folder. You can simply copypaste it from the Eng folder and translate that.

- The English stuff in the accessibility menu is due to some lines missing from the Spanish file ($UI_ACCESS_FAILURE_PENALTY, $MISC_RESTORE_DEFAULTS). Same thing for the save menu tooltips you posted in the other report. 
![saves](https://cloud.githubusercontent.com/assets/20359621/16708882/4d42f2c6-4601-11e6-80ce-552e6bde1615.jpg)
 You're probably missing many more lines as well...

- The rest are just bugs, from what I can gather.

**Comment by larsiusprime** [comment]
This should all be fixed in 2.0.8 now
