### ISSUE TITLE
Localization: missing files in language folders. Copying them from the English folder doesn't work.

### ISSUE THREAD

**Issue by LarsMadeMeDoIt** [larsiusprime/tdrpg-bugs#1197]
A while ago I noticed goodies.tsv and mods.tsv were missing from the Italian folder (and a few others). "Ok, no biggie" I thought "I'll just take them from the English folder and work from there" and then I forgot about it. Yesterday I actually started translating them, and found out that the text wasn't changing; it remains in English.

Languages affected: all except Japanese and German.

PS: in addition to goodies.tsv and mods.tsv Spanish is ALSO missing status_effects.tsv

**Comment by larsiusprime** [comment]
Excellent catch!

This one took a while to figure out.

So, because the files are missing at the time the game was compiled, they're not listed in the game's asset manifest file, which is what it checks for if a file exists or not. So even though you stick a new file there, it doesn't change that they're missing from the manifest. 

I'll put some dummy files in for now (duplicates of the english ones) that should fix the problem in the next patch.

**Comment by larsiusprime** [comment]
As a temporary workaround, you could create a blank mod, whose sole content is an locales/it-IT folder with your files, and that should override the bug in the asset manifest. Or you could wait for the next patch that fixes everything.
