### ISSUE TITLE
Bonus Levels all white even if not completed yet

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#1288]
I could've sworn this was in here already, but I'm not finding it by searching.

The bonus level labels in the main Bonus Levels dialog are all white, until you click in to each one to see its pass/perfect status.  I think they should change colour, a) to be consistent with the stars interface in the map and b) because otherwise if you forget which each one is called it's quite easy to lose track of where you are if you're playing through them all at the end rather than after each is unlocked.

2.1.2c - itch, Linux Mint 18.1 x64, HD mode@1920x1080 fullscreen

**Comment by IBwWG** [comment]
Also, I just noticed you can click the "select" buttons in the background even though the background is grey.  This helps, but it's a bit unexpected--normally the grey background stuff is not supposed to be clickable, right?  Otherwise it would not be darkened?

**Comment by larsiusprime** [comment]
I'll see what I can do!

**Comment by larsiusprime** [comment]
Okay, so what I did was to change the color of the text of the currently selected bonus battle to highlight in yellow so it stands out.

As for buttons being selected even when it's greyed out, it is a bit unexpected, yes, but it's a concession to user testing (users were strongly expecting to be able to close the left menu by clicking on it, and it doesn't harm anything to make that possible in this case).

Fixed in 2.1.4

**Comment by larsiusprime** [comment]
Oh I misread this, I see what you mean. Moment.

**Comment by larsiusprime** [comment]
![2017-01-23 15_48_16-defender s quest i](https://cloud.githubusercontent.com/assets/739064/22224200/6e5c7f5e-e183-11e6-8931-f9c59a733714.png)

I assume this the kind of thing you meant. It's in 2.1.4.

**Comment by IBwWG** [comment]
Yep, that's exactly it.  Sorry it wasn't clear at first.  :)
