### ISSUE TITLE
Custom gear PSI tax does nothing?

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#1304]
I made a sword with:

stat / 100% PSI TAX / easy, +range
stat / 0% PSI TAX / hard, +attack

Killing enemies with this sword on easy did not reduce the PSI payout to nothing.

Am I misreading how this is meant to work? There's only three difficulties listed as well in item editor, Easy / Medium / Hard. But there are four difficulties in game. Does Easy bundle together the first two difficulties in game?

Also, because it's too small a change to warrant it's own entry and I just noticed it:

Why is the healing spell icon now a sickly color green? The + is the universal symbol for 'add' or 'more'. Red is the color of hitpoints, I assume because red is the color of blood. The red + implies "Add / More Hitpoints."

**Comment by dqhol** [comment]
Doing some googling I see that there's been some sort of thing about not violating the Geneva Convention by using the Red Cross's flag, which is a clear red cross on top of a solid white square. It implies some association with the actual red cross, or something? So no putting that flag on hospitals in games, no putting it on medipacks or putting it on the side of ambulances, which Prison Architect was in violation of.

Hooowever... Defender's Quest's icon is clearly a plus sign on top of a silver/gray button, lacking the required white backdrop associated with the Red Cross. And it's not attached to traditional health services. Like eating food in Starbound / Stardew, same red plus with no white flag.

Do we really need to go to such lengths as to remove the iconic (Add/More) (Hitpoints/Blood) impression that is the red plus sign from videogames altogether? I would assume a red + on it's own can't possibly be protected, not without the accompanying white background to clearly designate it as being the Red Cross's brand. There's no way that trademark could arguably be breached here. :P Perhaps we shouldn't be too eager to give up an incredibly generic yet understood symbol that's vital to conveying a message at a glance.

**Comment by larsiusprime** [comment]
Okay, found the cause:

PSI Tax is only applied for items with the following special ability types:

* RULE
* AUGMENT_SPELL
* REPLACE_SPELL
* ALL_FLAVOR
* RANDOM_FLAVOR
* TRIGGER_HIT

And only when applied to the Mcguffin, apparently. I'll try to put in a quick patch.

As for the heal icon, I don't really feel strongly either way. I like both icons about the same, I'm not particularly attached to the Red, and lots of other high profile games (including many AAA titles) have been avoiding borderline cases by making their red crosses slanted or otherwise stylized, or changing the color to red or blue.

**Comment by larsiusprime** [comment]
This won't make the launch but I'll address it ASAP.

**Comment by ManDude** [comment]
If I recall correctly, Casual just grabs Easy and halves the stats of the enemies.
