### ISSUE TITLE
Strange Monument shop doesn't appear

### ISSUE THREAD

**Issue by jamespicone** [larsiusprime/tdrpg-bugs#1317]
Operating System: Windows 7
Browser/Download: Download
Demo/Full?      : Full Version
Version #       : 2.1.5

I just did all the Strange Monument codes, getting the "you get an item!" screen each time for gold and unobtanium skulls. But the Strange Monument shop doesn't seem to be appearing; I've left the screen and come back, I've unequipped and re-equipped the Book of Secrets, and I've tried quitting the game and coming back.

Entering codes again doesn't result in getting an item, so it definitely thinks the code has happened.

I'm attaching my exported save file. Glancing at it, it looks like maybe I got given skulls of the wrong type?

[noshop.txt](https://github.com/larsiusprime/tdrpg-bugs/files/818436/noshop.txt)

**Comment by Bremen65** [comment]
I'm having the same issue, it looks like I may be getting bronze skulls rather than gold ones.

Operating System: Mac 10.10.5
Browser/Download: Download
Demo/Full? : Full Version
Version # : 2.1.5a

**Comment by larsiusprime** [comment]
This bug is fixed in version 2.1.7, patch due soon.  For some insane reason, it was granting stone skulls by mistake.

I've also included a script that fixes old (broken) saves affected by this bug. 

The logic is:
* Count how many gold & unobtanium skulls you have
* Look at any books you have and convert their value in terms of the above skulls
* Check what code triggers you've unlocked
* Calculate how many gold & unobtanium skulls you have earned
* Compare that to how many are actually in your inventory (loose and in the form of books)
* Grant the difference

The side effect of this is that you will have some extra stone skulls potentially. Oh well, who cares, enjoy the bonus. I'd much rather have a positive side effect of a bug than a negative.
