### ISSUE TITLE
Simplify speed stat displays

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1364]
> Instead of showing "14 speed," it could show "1.4x speed" instead, no? Since I believe the way it works is "base_cooldown / (speed / 10)". This would probably make it way less confusing for newbies.

**Comment by larsiusprime** [comment]
It's a good idea.

**Comment by larsiusprime** [comment]
I'll put it on low priority for now and circle back to it for the sequel. It's a good idea, but I have to weigh it against the original reason I think we went with the "10 points per unit of speed" display. Although it's more cumbersome, we thought that people would see "+0.2X to speed" and feel like that was a bad deal compared to the same thing displayed as "+2 to speed."

(Increasing speed is one of the single most valuable stats you can invest in, so we wanted to incentivize it)

**Comment by DeeDeeG** [comment]
As a user, I found the "10 more points means you go twice as fast" notation a little hard to understand.

First play-through, I felt like I was investing in something I didn't understand, knowing it would be good (on faith) but not really knowing what to expect. It's also not the kind of boost you can subjectively notice observing the gameplay.

I mostly boosted my individual attacks instead of boosting speed first time around.

When I went in later and did the math, I found that the DPS would be higher, all else being equal, if I invested in speed vs. boosting the damage of individual attacks for, say, a Berserker. But... I couldn't be sure I was doing the right math! The explanation wasn't really clear enough for me to feel confident in my calculations.

I would like best any text, if possible, that does both of these:

- Comes off intuitively for folks without a background in math
- Hints pretty clearly at a mathematical formula that it uses (if the player cares about the math)

Distant third priority for me would be not scaring off players by saying "1.x speed"... but I am more of a math person, comfortable with these calculations and instinctively want to hash out the boost in my head, so I am biased toward my way of interpreting the stats/abilities. (That's why I say, make it more intuitive for non-math folks as first priority. Simple language, hopefully in a way that sounds powerful without over-selling it.)

**Comment by DeeDeeG** [comment]
For what it's worth, it does feel more "RPGish" (I guess a bit like D&D) to have integer stats in your "character sheet", rather than having a decimal multiplier in the stats screen.
