### ISSUE TITLE
Main skill descriptions should update according the skill upgrades acquired.

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1436]
i.e. let's take Zerk's Slash skill, which by default is a basic damage skill. Now, if we upgrade the Critical skill upgrade, for example, the new Slash skill description should update to reflect that, meaning it should now have a ``Critical: 5%`` line in the middle and a description of the Critical effect at the bottom.

Also, this means that it'd probably look better if the asterisks were just cut and replaced with the status name. So, instead of at the bottom saying ``*Damage is 2x normal`` it would say ``Critical: Damage is 2x normal``.

This should also apply in-battle, since there's currently no way to check skill upgrades during them.

**Comment by larsiusprime** [comment]
Great idea. On it.

**Comment by larsiusprime** [comment]
![2018-12-05 14_51_05-Defender's Quest 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/536bb941ebef97b1f959bdc4/125516c66e82c728ace21e0d46bac4cb7bcfd2fbc2b9ea03f509cfc1787977266420a62d758be72dad0568413e1a1bef05485d56e0ebc969f9ec6923ce4e01ffd46e5926973f14acedd04ae908bd728a198cb3b5d818c7ee2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee54955a0103664ee7f307e55d9.png)

I've got this now.

I'm trying to make it so that it will show specifics about the effects too.

**Comment by larsiusprime** [comment]
![2018-12-12 10_37_17-Window.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/536bb941ebef97b1f959bdc4/125516c66e82c728ace21e0d46bac4cb7bcfd2fbc2b8ed03f50dcfc77e7976246433aa25748af46af3006b1300051bff054a5556f9fa8f79f7b43970df0e5ebbd86a0d75903414a5ead618b913a632c91edbe2e3d7158abd7f37ed998e48341f001c8df95e37a69c48cf5bf159ac.png)

There we go
