### ISSUE TITLE
Overworld Dollars display hidden while journal is open

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#1437]

**Comment by larsiusprime** [comment]
Thanks for pointing this out!

From the looks of it, hiding the dollars display (formerly scrap) is intentional, but I forgot to add similar code to hiding the star coin display as well, which is what makes this so noticeable.

I think the reasoning was that the money icon/text either obscures some UI element that can appear with the Journal or competes with it for attention.
