### ISSUE TITLE
It is not possible to switch back to windowed mode from fullscreen without restarting the game

### ISSUE THREAD

**Issue by adasko1984** [larsiusprime/tdrpg-bugs#1459]
> Windows 10, 64 bit
> Downloaded (steam), full
> Dell Inspirion 5577 (i5-7300HQ, 8GB RAM, NVIDIA GeForce GTX 1050 4GB)

Steps:
1. Start the game.
2. In Video settings select "Fullscreen" and apply changes.
3. Return to game and go back to settings.
4. Change back to "Windowed" and apply.

Actual:
Step2: Before game switched to fullscreen mode it gets minimized to taskbar.
Step3: You need to go back to game, by clicking on it on taskbar. Video options are very limited (resolutions are missing)
![fullscreen](https://user-images.githubusercontent.com/25862457/48094044-6284ec80-e211-11e8-803e-1a9b01d91ff4.jpg)

Step4: Game is again minimized (it happens each time user is using "fullscreen mode" and enters video settings). Game is still in fullscreen. To go back to windowed mode user has to restart the game.

Expected:
In step 4: Game is again in windowed mode without need of restarting it.
It would be very good if game in fullscreen mode do not get to taskbar each time user enters "Video" settings.

**Comment by adasko1984** [comment]
I checked with DQ1 - I have the same problem. 
Additionality I realized that something pops up when I eneter Video settings (in DQ2 as well)
screen: 
![screen_dq1](https://user-images.githubusercontent.com/25862457/48217644-393a9c80-e388-11e8-8007-610bfb54c7c0.jpg)
(couldn't get any better screen with that popup)

**Comment by larsiusprime** [comment]
I'll try to work on this, I was always unsatisfied with the first game's full screen support. Might take some tweaking...

**Comment by larsiusprime** [comment]
Couple of things here:

- The resolutions are "missing" from the fullscreen options because all it does is stretch the window to fullscreen-borderless at whatever resolution you already have. 
  - I *might* consider adding the ability to pick a resolution and do dedicated fullscreen, but I had issues with it before when I did DQDX. If there's a lot of demand I'll investigate my options.
- The Fullscreen/window toggle issue doesn't seem to happen if I compile with the OpenFL8 stack. I might have that bug solved at least.
- The cmd window popping up is the game running the wmic tool to get information about your monitor's capabilities. This may or may not be necessary anymore, I might be able to do without it, or just suppress the cmd popup in invoking it.

**Comment by larsiusprime** [comment]
Confirmed that wmic is unnecessary when I use the OpenFl 8 stack, because it is properly able to query screen resolution directly.

Very likely using the OpenFl 8 stack in the next build will fix the two main issues you had: not being able to toggle back and forth between windowed/fullscreen, and the errant cmd window popups (as they are now unnecessary). I'll table the custom fullscreen resolution issue for now, but I can revisit it later.

I'll stick this as "please verify" for now. When the next build drops on Steam, please try it and if this is fixed, leave a comment on this issue.
