### ISSUE TITLE
Cutscene Artifacts

### ISSUE THREAD

**Issue by meganbednarz** [larsiusprime/tdrpg-bugs#431]
BASIC INFORMATION:
Operating System: Windows 7 x64
Version #       : 0.1.9 build 35
Resolution: 1280 x 720 windowed
Graphics card: Nvidia GeForce GTX 260

A couple of issues here: 
1) Shadow layer appears to have glowing square borders. 
![0 1 9-35_cutscene_lightbox](https://cloud.githubusercontent.com/assets/597059/9077459/e9225afc-3af3-11e5-99e2-eac94c698753.png)

2) Unnamed plague victim in first cutscene has some weird artifacts maybe due to resizing. All of her images shadow/highlight layer seems to have this.
![0 1 9-35_cutscene_weirdartifacts](https://cloud.githubusercontent.com/assets/597059/9077463/f4c993fc-3af3-11e5-8f74-ee0f5aedc285.png)

**Comment by larsiusprime** [comment]
Right, so these bugs I'm well aware of. They're fundamental limitations of OpenFL "legacy"'s blending issues not behaving the way they should (improperly detecting color information in transparent pixels that should be ignored entirely).

This is fixed on OpenFL "next," however text support isn't fully ready in OpenFL "next" yet, so I can't switch the game over. But when I do, this bug will vanish entirely. On my local builds using next it's entirely gone and the cutscenes look great.

As a temporary measure I might be able to fix this by finding a script to do some manual surgery on my PNG files and make sure all the transparent regions are 0x00000000 instead of 0x00(garbage).

**Comment by meganbednarz** [comment]
Seems fine to just log it in a "Known Issues" list.

**Comment by larsiusprime** [comment]
Yeah, you know what? Let me start a meta-issue for just such a thing, with links to individual issues like this one.

**Comment by larsiusprime** [comment]
Hmmm, or maybe that's what labels are for.

**Comment by larsiusprime** [comment]
Check it out!

![alphabug](https://cloud.githubusercontent.com/assets/739064/9086904/1772136c-3b4d-11e5-8e54-f7c74294a886.png)

That's what the "plague girl" 's light layer looks like when you separate it into color and alpha channel. So because OpenFL legacy doesn't premultiply alpha correctly, it's incorrectly reading those color values that are on the transparent bits of the image.

So I think I can write a quick batch script to clean up these light layers; there'll still be some trace artifacts and we'll need to move to OpenFL-next eventually, but it should make things a lot better in the interim.

**Comment by larsiusprime** [comment]
Okay, I've gotten this as good as it's going to get in legacy. There's still artifacts but hopefully it will be tolerable in the short term until we can move onto next.

**Comment by larsiusprime** [comment]
This is fixed now as we've permanently moved to -Dnext!
