### ISSUE TITLE
Skills not learned will still be lighted up

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#598]
![dq1](https://cloud.githubusercontent.com/assets/7569514/12463353/f71368c6-bfba-11e5-8875-ee9cd2eecd9a.png)
I expected the empty skill bar to not light up as I reach the required boost level.

**Comment by larsiusprime** [comment]
This is intentional behavior because we've replaced the boost bar in the original DQ1 with the boost menu here. It's important that there's still feedback for what boost level you're at and what skills you *could* have unlocked -- we don't print the name of skills you haven't learned yet.

I'm open to discussing changes to this, but at the very minimum I want the gem to light up. I'm not sure if it's better to leave the skill bar lit up (but empty) or leave it dark.

**Comment by larsiusprime** [comment]
After some thought I think I'll close unless other users are confused -- I think the feedback works in this design.

Thanks for bringing it up tho! Do feel free to present other issues of this sort.
