### ISSUE TITLE
Cutscene to map transitions don't change music

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#602]

**Comment by larsiusprime** [comment]
This is probably intentional. There are several places in the game that it's intentional for music to carry over into the overworld (helps with pacing). You'll notice this same behavior in the original game.

Or are you saying that this happens with EVERY cutscene, or on cutscenes you rewatch through the movies interface?

**Comment by ManDude** [comment]
It's happening with every cutscene I've gotten. This does not happen with cutscenes from the movie menu.

Hmm I really don't recall this feature in-game but maybe it's just so minor (and effective!) that I forgot it existed. :P

**Comment by larsiusprime** [comment]
Just ran through, and everything plays out the way I intended. Thanks for the issue though!
