### ISSUE TITLE
Accessibility screen text looks wrong

### ISSUE THREAD

**Issue by cocoajam** [larsiusprime/tdrpg-bugs#674]
Waffle is a lot harder to do more than browse the errors, while Github is a lot better to edit and message with, imo. First time using both so apologies, but I enjoy the game and look forward to 2 enough to learn it!

**Comment by cocoajam** [comment]
Pips on that screen are cut off on the right hand side for Rewards, and Penalty menu

**Comment by cocoajam** [comment]
Also Typo on Video menu screen. Highlight, is spelled hilight on bottom right of the menu

**Comment by larsiusprime** [comment]
Can you post a screenshot of the cut off pips? You can drag and drop an image directly into github. At the risk of being redundant -- the print screen key should copy+paste the screen (in windows) and from there you can paste it into MS Paint, photoshop, etc.

**Comment by cocoajam** [comment]
[DQ Text Errors.zip](https://github.com/larsiusprime/tdrpg-bugs/files/222625/DQ.Text.Errors.zip)

**Comment by larsiusprime** [comment]
Okay, took a look, and I think most of these are fixed already, you're just using a really old version of the game. The blog has updated links to build, 0.4.5, and bleeding-edge nightly builds are in this folder:
https://drive.google.com/drive/folders/0B82nNNq_hucHOEV1eF9pQ1B1eXM

(Version 0.4.9 has a crash but that should be fixed in 0.5.0)

The only one that wasn't fixed was the accessibility menu, which I've updated a bit to look slightly cleaner. That will be in build 0.5.1.
