### ISSUE TITLE
Save your "opening play" (all summonings before 1st wave spawns)

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#682]
I find it a bit chore-ish (on any TD game, actually) to set up all my defenders, start the game, and then realize after I start getting attacked, that one tweak could have made all the difference.  DQ is already great in that you get 100% refund before the first wave, so that if you realize the mistake before the 1st wave, it's easy to "edit" without redoing everything.  But it'd be even better if there were an option to, when you fail or quit a battle, restart with the same summonings so you don't have to redo them all if you're mostly happy with them.

**Comment by larsiusprime** [comment]
I definitely have meant to do this for a long time.

I was wondering if it would be best to do this, or to save a full replay of
your inputs, and lets you restart the battle with that replay until you
decide to "break" it and start playing fresh.

On Sat, Apr 23, 2016 at 9:47 PM, IBwWG <notifications@github.com> wrote:

> I find it a bit chore-ish (on any TD game, actually) to set up all my
> defenders, start the game, and then realize that one tweak could have made
> all the difference. DQ is already great in that you get 100% refund before
> the first wave, so that if you realize the mistake before the 1st wave,
> it's easy to "edit" without redoing everything. But it'd be great if there
> were an option to, when you fail or quit a battle, restart with the same
> summonings so you don't have to redo them all if you're mostly happy with
> them.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/682>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
I guess you already are using flixel replays according to another thread, so it would maybe even be less work to do it that way than save just the positions?  OTOH with a replay, the user has to wait for the replay to play through.  But I think you can increase the flixel framerate temporarily to solve that, I've never tried & not sure which way you do it for the game's slomo/speedup already.  Although I guess that wouldn't be an issue because you'd just tell it to keep paused.

**Comment by larsiusprime** [comment]
The flixel replay system isn't quite robust enough to handle this on its own -- DQHD is resolution independent, but flixel replays just store raw keyboard / mouse input. What's really needed is an upgraded replay system that is driven by *actions*. I currently have a huuuuge PR in the queue for FlxActions, and when that gets reviewed then it'll be an obvious time to add a new recording system, which is probably what I'll wind up using in DQHD.

Since I need to focus on shipping soon, I think this might be a good M.V.P. in the meantime, and provide most of the value for very little of the cost:

1. Battle starts
2. You place some defenders and boost some of them
3. First wave arrives
4. Your placement/boost/targeting layout is silently saved
5. You quit, restart, or lose
6. You return to that same battle and difficulty without starting a different one or respecc'ing any characters in the party screen
7. "Use your last starting layout? Yes / No" --> Yes
8. Bam bam bam bam bam --> Azra summons & boosts everyone to match the old layout

This is guaranteed to work as long as the game can assume the characters have the same skills and Azra has the same amount of PSI, that no enemies have yet arrived, and so forth.

For boss battles (where the map STARTS with a boss already placed) we'll have to go with something like "first blood" (first attack landed by either defender or enemy) that will trigger the placement freeze.

What do you think? This could be implemented in a day, easy, but a full replay would be more involved for sure.

**Comment by IBwWG** [comment]
That sounds pretty good to me.  (BTW, I'd seen your actions PR and am interested in it, but it's not yet on the immediate radar for me.  A VCR based on them would be very cool though, and probably a heck of a lot more efficient as well as useful in terms of analyzing its data.)  As for the assumptions, if there's a way Azra's starting PSI can go down, I guess the game could check for that and invalidate the save if so.  Having extra skills, that shouldn't be a problem, right?

**Comment by larsiusprime** [comment]
The main issue with extra skills is people could respec themselves so that they have less boost skills then they did originally.... which I suppose wouldn't be a problem because you can still boost to that level even if the skill isn't there. You can't dismiss party members, and boost costs are fixed for the whole game, and no items or skills that I know of affect azra's PSI stat. So the only thing we need to use to invalidate the starting position is if you've gone to another battle or another difficulty (and thus started a new layout).

**Comment by ManDude** [comment]
Maybe have the defenders be placed in tile IDs so it won't need to store resolution.

**Comment by larsiusprime** [comment]
Okay this is implemented. It's currently not saved to disk, but the basics should work within a single game session.

- [ ] defender position
- [ ] defender boost levels
- [ ] defender targeting
- [ ] defender skills disabled manually

This is saved any time you do anything with a defender prior to the first wave appearing. 

These things will reset your saved layout:

- [ ] starting a different battle, or the same battle on a different difficulty
- [ ] quitting to the title screen

Expect this in 0.5.6

**Comment by IBwWG** [comment]
Super!  Thanks for prioritizing this, testing will be way easier too as you pointed out in the other thread.  :)

**Comment by IBwWG** [comment]
This doesn't seem to work on 0.5.7win7x64.  On ozimal's coat just now, started extreme, put all my defs, started, then half way through went 'restart battle' without leaving.  It asked me if I wanted to restore, and I said OK, but no defenders got placed.  I went 16X until the battle began and still they weren't placed.

**Comment by IBwWG** [comment]
Additionally it would be cool if, before the battle has begun, recalling a defender has no delay for getting the psi back.  :)

**Comment by IBwWG** [comment]
On second thought, resetting the saved layout in either of those cases (except starting a different battle) doesn't seem helpful.  Also it gets reset after a crash, can that not happen?  (Just call flush() when the first wave hits, yeah?)  After doing a battle on advanced, going back on extreme I may not want the exact same layout, but sometimes close enough that it beats a reset.  Maybe each battle could have its own save (regardless of difficulty)?

**Comment by larsiusprime** [comment]
I think I might have this disabled for boss battles right now. I think I'll
go ahead and flip that switch off. Can you confirm it works in other
battles?

On Fri, Apr 29, 2016 at 9:00 AM, IBwWG <notifications@github.com> wrote:

> On second thought, resetting the saved layout in either of those cases
> (except starting a different battle) doesn't seem helpful. Also it gets
> reset after a crash, can that not happen? (Just call flush() when the first
> wave hits, yeah?) After doing a battle on advanced, going back on extreme I
> may not want the exact same layout, but sometimes close enough that it
> beats a reset. Maybe each battle could have its own save (regardless of
> difficulty)?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/682#issuecomment-215724914>
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
Makes sense.  I didn't check what the pattern was, but it sometimes did, sometimes didn't.  I didn't know there were such things as boss battles internally.  :)

**Comment by larsiusprime** [comment]
Yep, you'll notice there's a special targeting mode that only appears in boss battles, too.

**Comment by IBwWG** [comment]
Ah yes!  I had seen that, just not noticed that it was only sometimes there.

**Comment by IBwWG** [comment]
0.6.7, win7x64, HD mode@1704x960windowed

On the second-last battle vs zelemir (on the longer path, non-NG+), I passed nonperfectly on extreme.  Went back to try again, didn't save.  Part way through, Azra took damage so I started again within the battle, but again it didn't save.  (Or if it did, it didn't ask me to load.)
