### ISSUE TITLE
Crystals missing from night of knights map on extreme

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#718]
0.5.7win7x64

Before there were at least some on extreme, IIRC...if not, the tutorial guy shouldn't tell you to use them ;)

**Comment by larsiusprime** [comment]
They're definitely missing. You can see that the map preview differs from what you actually see in-game.

**Comment by larsiusprime** [comment]
Interestingly enough, this seems tied to resolution. It doesn't happen in 800x600, but it does happen in 1280x720, for instance.

**Comment by IBwWG** [comment]
Even though I am not familiar with your game's particular internals, I do find that interesting too :)

**Comment by larsiusprime** [comment]
Okay, figured it out. The crystals were in the wrong position by an offset exactly equal to the size of the left sidebar in 16x9 layout mode. Finally figured out it was because the battlefield offset was being applied to them twice, because -- I was adding them to the battlefield twice, as well. So when it goes through and shoves everything over, the crystals and only the crystals were being shoved twice as far.

Fixed in 0.5.8
