### ISSUE TITLE
Need to pad maps with auto-tiles in original art mode

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#723]
At 1920x1080 on fullscreen mode, the map is scaled nice and big, but when I switch to windowed, which lowers the res one notch, battle maps look like this:

![dq-small-map-and-wrong-placement-offset](https://cloud.githubusercontent.com/assets/16719964/14927213/d7912a12-0e50-11e6-9158-bdd4e0464284.png)

0.5.7win7x64.

**Comment by larsiusprime** [comment]
This isn't actually a bug -- in original art mode, the game refuses to scale the pixel art by a factor less than a clean 2X, or else it looks terrible. The map is 14 squares tall, and each square in original art mode is 40x40 (made of four 20x20 subtiles), so that's 560. Technically speaking, the lowest viable resolution for clean upscaling is thus 1120, which is one full square too big even for 1080p!

So in 1080p we cheat a bit by making the squares 38x38 (made of four 19x19 subtiles) so that the total height of the map is 1064 pixels, giving 16 pixels to spare.

Any lower than 1080p and no amount of cheating will help us. It looks a bit awkward, but it's the best we can do. I am planning on auto-padding the map borders with extra tiles in a way that makes it look less empty, though (and stops people walking around the edge)

**Comment by IBwWG** [comment]
Fair enough, thanks for the explanation.  :)

**Comment by larsiusprime** [comment]
- [ ] Bug: crystals misplaced & start locations punch "holes" in the map due to wrong offset
- [ ] Bug: maps don't tile consistently -- some will pad, others won't

**Comment by larsiusprime** [comment]
Fixed in 0.6.3
