### ISSUE TITLE
Able to place crystals on enemy path

### ISSUE THREAD

**Issue by ManDude** [larsiusprime/tdrpg-bugs#775]
![dq03](https://cloud.githubusercontent.com/assets/7569514/15622504/473de12c-2461-11e6-96e3-7822877f11cb.png)
![dq03-1](https://cloud.githubusercontent.com/assets/7569514/15622505/4765ded4-2461-11e6-9aa5-09583a17607c.png)

**Comment by larsiusprime** [comment]
Fixed in 0.7.8.

Thanks!

**Comment by IBwWG** [comment]
Although, having 'grown up' with this bug, I didn't know you shouldn't be able to.  (Is there something in the game that tells you that?)  Anyway as of 0.7.8 I'd suggest an X'd-out cursor when you're over the path, because otherwise it just seems to not work "for no reason".  (Just to be consistent with other X'd-out cursors in the game when you're trying to do something you shouldn't be able to.)
