### ISSUE TITLE
No Zeal even though defenders are near by

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#793]
Shouldn't these be pre-zealing my dragons?

![dq-no-zeal](https://cloud.githubusercontent.com/assets/16719964/15678137/732ebad8-274d-11e6-973c-03a19ee9431a.png)
0.7.8, win7x64, HD mode@1704x960windowed

**Comment by larsiusprime** [comment]
No, actually -- because Zeal has such a long cooldown time, players of the original game lobbied for (and got) a fix where Zeal is only cast if:

- A defender is in range and needs to be healed
- An enemy is in range and could be attacked
- An enemy is in range of a defender that is in range of being buffed

If everyone in range is at full health and no enemies are in range of the healer or any of the defenders the healer can buff, they will save the Zeal attack so as not to "waste" it.

**Comment by larsiusprime** [comment]
Good question though!
