### ISSUE TITLE
Book of Blood prevents stronger bleeds? [FALSE]

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#828]
Not sure if this is a bug, but Book of Blood says "Bleeding: +25% damage, lasts forever."

However, my Slak can apply +55% bleeding and he never, ever does with BoB equipped. Usually with debuffs, the stronger debuff will overwrite the weaker one. Is this a bug or a tradeoff?

**Comment by larsiusprime** [comment]
Debuffs don't override each other, they actually combine using a rule called "conservation of potency-duration." Put simply, it generally ups the whole effect to the stronger effect and then converts the weaker effect to the same level by compressing its duration.

The algo could be buggy. Do you notice the bleed effect's duration increasing ever?

If it is a genuine bug it miiiiiight be because since bleeding lasts forever, the algorithm hits a discontinuity (duration is -1) and doesn't know what to do, since the effect literally lasts forever.

...Which would suggest this bug is also in the original game. Is it?

**Comment by ManDude** [comment]
So does this mean the stronger bleed should REPLACE everbleed, and when bleed ends it gets replaced by everbleed again?

**Comment by larsiusprime** [comment]
That would be the best logical solution, but I'm not 100% sure how I would implement it.

The only way I can really think of is to make EVERBLEED a separate flavor that's not related to normal bleed.

**Comment by dqhol** [comment]
I tried it against a few enemies in the final battle, didn't notice their bleed going up past 25%. Might have just been a coincidence, though. I loaded up the Super Sheep battle to let Slak wail on it, bleed wound up going to +55% Lasts Forever. So never mind this one, sorry. :(
