### ISSUE TITLE
Cool, creepy, endgame red rock replaced by generic desert in DQNew in every level?

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#834]
![ze](https://cloud.githubusercontent.com/assets/19625520/15766845/f1727aaa-2910-11e6-95bd-d037007ea73e.png)

Top: DQ old
Middle: DQ New
Bottom: DQ New-But-Old

These levels look a lot worse and less intimidating without the painted rock

 Also, not sure if it's worth a bug report on it's own, but is it my imagination or is there significantly less level decoration? There's barely any decorative objects anywhere on the tiles.

**Comment by dqhol** [comment]
Oh, it's a naming/file error. tile_dark_obsidian in HD tiles is sand, but red rock in DQOld. I hope the HD version of this didn't get lost. :(

**Comment by dqhol** [comment]
I dunno what priority to assign this, but it would be nice to have some clarification if it's intentional that all the cool old red obsidian levels are now desert levels. :P

**Comment by dqhol** [comment]
So.... bug or feature? :(

**Comment by dqhol** [comment]
Bumping two months later~

**Comment by ManDude** [comment]
I think this is intended unless there is another sand tileset which would make this one a duplicate tileset.

**Comment by larsiusprime** [comment]
Oh sorry about ignoring this. Yeah, this was intentional. Basically I didn't have any new art for the weird red rocks, and decided to just go with something that matched the overworld a little better.

I might try to more closely match the rocks in the next patch, maybe not. Not a huge priority at the moment as I've got a few other things spinning on my plate, and I'm long overdue for an update.

**Comment by larsiusprime** [comment]
For better or worse, I just don't have time to fix this. I'd rather put that effort into DQ2 rather than noodling on DQ1 forever.
