### ISSUE TITLE
High Priest can be damaged.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#837]
![ze](https://cloud.githubusercontent.com/assets/19625520/15767232/51e09b08-2914-11e6-9a13-4b9017c9266c.png)

**Comment by dqhol** [comment]
Also, now that I'm looking at it, is the description text an intentional edit? A rewrite?

![ze](https://cloud.githubusercontent.com/assets/19625520/15767271/a5e3c180-2914-11e6-9b29-7c0d69df7bef.png)

**Comment by larsiusprime** [comment]
Did you have to do anything special to damage him? Looks like you'd still
have to go to extreme lengths to actually finish him off, but yeah, I
should fix that.

And yeah, that modified description is intentional. James went in and
updated the flavor text in a lot of places to king of tie together various
loose ends in the story.

On Thu, Jun 2, 2016 at 9:52 PM, dqhol <notifications@github.com> wrote:

> Also, now that I'm looking at it, is the description text an intentional
> edit? A rewrite?
>
> [image: ze]
> <https://cloud.githubusercontent.com/assets/19625520/15767271/a5e3c180-2914-11e6-9b29-7c0d69df7bef.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/837#issuecomment-223478592>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-BwqBBWOQSwfH8FvJvv2omZMZ7-7ks5qH5bmgaJpZM4ItKIe>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by dqhol** [comment]
I plunked down a maxed Berserker. Did nothing to him. Plunked down a maxed Knight, suddenly he takes damage. Plunk down an ice mage and dragon, they can damage him now too.

Seems knights are the trigger of making him damageable.

**Comment by IBwWG** [comment]
0.8.4, win7x64, HD mode@1704x960windowed
Damaged him before he reached the knights:
![dq-hp-damage](https://cloud.githubusercontent.com/assets/16719964/15806658/9322d938-2b48-11e6-94a0-6dab70290c28.png)

**Comment by larsiusprime** [comment]
Fixed in 0.9.3
