### ISSUE TITLE
Mystery health bars at top during PUSHBACK

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#842]
0.8.2, win7x64, HD mode@1704x960windowed
![dp-hand](https://cloud.githubusercontent.com/assets/16719964/15790367/41d6b374-29d1-11e6-8a26-01be01404fa9.gif)
This is at 1X btw.

**Comment by IBwWG** [comment]
0.9.0, win7x64, HD mode@1704x960windowed
experienced again on Following Zelemir.

**Comment by IBwWG** [comment]
2.0.8b, win10, 1920x1080 fullscreen HD mode.  Experienced without push back active, but only 1-3 bars the times I've seen it.  Currently in the last few levels of the game on NG+

**Comment by IBwWG** [comment]
Just saw it again and happened to pause, same system and setup:

![dqmysterybar](https://cloud.githubusercontent.com/assets/16719964/20196404/95a59af0-a768-11e6-8206-a9c198ab3f85.png)

**Comment by IBwWG** [comment]
About 6 frames later it disappeared.

**Comment by IBwWG** [comment]
A few seconds later, another appeared and I paused again:

![dqmysterybar2](https://cloud.githubusercontent.com/assets/16719964/20196499/f02f5a88-a768-11e6-92c8-5889f3f7e737.png)

This one appeared about 10 px to the left of where you see it, slid over to the right, and then stopped.  Was at 2x when it happened.

**Comment by IBwWG** [comment]
Happened about 7 more times this fight...also the push back did cause it once.

**Comment by IBwWG** [comment]
And more.  Push back causes it consistently, also it seems Markos' version does too.

**Comment by codingthat** [comment]
This also happens while not on pushback, on 2.1.5a on Linux Mint 18.1 x64 @ 1920x1080:

![dq - health bar at top](https://cloud.githubusercontent.com/assets/26723818/25082080/a70777ca-234e-11e7-974d-2bb4281a6913.png)

Here it's at 16x but I also saw it later at 1x.  Happened many many times that battle, showing health bars of various ranges, and often more than one at once.  Also when they made it further along the maze.  Come to think of it, it seems to have to do with being near a knight, so it's probably related to both push back and knock back--if the knight knocks them back off the bottom of the screen, or something?  (I mean, just visually, as part of their falling backwards arc--because later in the maze they're not actually knocked off the bottom, but to the right.)

**Comment by larsiusprime** [comment]
I think I've fixed this.
