### ISSUE TITLE
Gold skulls already obtained in first run can be re-obtained in NG+

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#903]
0.8.4, win7x64, HD mode@1704x960windowed

I had already gotten the 1-2-3-5-8-... sequence gold skull the first time around, but when I input that just now in the desert, it gave me one anyway.

**Comment by larsiusprime** [comment]
Okay, so it was tracking these separately for normal and new game+.

There's no way to fix your skull counts, but I can at least fix this so it won't happen for any new players, so only testers with save files used in the beta will have extra skulls in their inventory :)

Now it just tracks the trigger progress in the regular game progress tag, regardless of whether you're in normal or new game+.

Fixed in 0.8.9
