### ISSUE TITLE
German Translation: Make the main char female :-)

### ISSUE THREAD

**Issue by commel** [larsiusprime/tdrpg-bugs#972]
It says librarian, but in German it has an own form for females so it would have to be: "Bibliothekarin".
![screenshot_20160609_205901](https://cloud.githubusercontent.com/assets/1015465/15942547/21ca1eb4-2e85-11e6-9b46-92a33369609a.png)

**Comment by ThomasFaust** [comment]
agreed

**Comment by commel** [comment]
Also make her a "Waldläuferin"
![screenshot_20160609_213339](https://cloud.githubusercontent.com/assets/1015465/15943555/dfdeb0c8-2e89-11e6-9659-10411ccf1cde.png)

**Comment by ThomasFaust** [comment]
Nope to that. If you have more than one ranger and some of them are male, this doesn't work. The job titles are plural, not masculine.

**Comment by commel** [comment]
Good to know :-) This is my first time Defender's Quest on Linux without Air!

**Comment by larsiusprime** [comment]
If it helps, all of the character classes are single-sex. We were originally going to add male/female versions a long time ago, but it got cut from the original game and for the DQDX update we decided just to keep the same basic feature set. It could theoretically be supported if the mod community really wants it...

In any case, my policy is that if the language in question has an acceptable neutral gender word for the class (or "male-but-becoming-more-neutral" -- think "actor" instead of "actress") then I prefer to use that one. Within the acceptable and common use standards of the language itself, of course.

**Comment by ThomasFaust** [comment]
I'd stick with "Waldläufer" (and, for that matter, "Eis-Magier"), then. It's that "male-but-becoming-more-neutral" thing you mentioned.
